# Generated by Django 5.0.2 on 2024-03-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_customer_profile_pic_customer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
    ]
