# Generated by Django 5.0.2 on 2024-03-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_product_image_alter_customer_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descirption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Management Software', 'Management Software')], max_length=200, null=True),
        ),
    ]
